<h2>Three Types of Indexing Supported </h2>

In [5]:
import numpy as np

a = np.arange(1,20,3) 
b = np.arange(15)
ax = np.array(b.reshape(3,5))
print("a = ",a,"\n")
print ("ax = ","\n\n", ax)

a =  [ 1  4  7 10 13 16 19] 

ax =  

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


<h3>field access (1-d array)</h3>

In [42]:
a[[1,4]] 

array([ 4, 13])

<h3>field access (multi-dim array)</h3>

In [43]:
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] 

array([ 1, 14])

<h3>basic slicing (1-d array)</h3>

In [44]:
a[2:7:2]

array([ 7, 13, 19])

<h3>basic slicing (multi-dim array)</h3>

In [46]:
ax[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

<h3>advanced indexing</h3>

In [48]:
ay = np.array([[2,4],[1,3]])
a[ay]

array([[ 7, 13],
       [ 4, 10]])

<h3>getting the corners of the array as a 2-d array</h3>

In [49]:
rows2 = np.array([[0,0],[2,2]])
cols2 = np.array([[0,4],[0,4]])
ax[rows2,cols2]

array([[ 0,  4],
       [10, 14]])

<h3>getting corners using slicing</h3>

In [50]:
ax[0:3:2,0:5:4]

array([[ 0,  4],
       [10, 14]])

<h3>Can combine slice for row and advance indexing for column</h3>

In [52]:
ax[1:3,[2,3,4]] 

array([[ 7,  8,  9],
       [12, 13, 14]])